Repository grpc-ecosystem/grpc-httpjson-transcoding, pull requests merged in 2022-09, with the labels that each got.

#77 Update OWNERS
  OWNERS
Labels: lgtm, approved, size/XS, do-not-merge/invalid-owners-file

#78 Fix Struct proto service config in unit tests
  test/json_request_translator_test.cc
  test/response_to_json_translator_test.cc
  test/testdata/bookstore_service.pb.txt
Labels: lgtm, approved, size/L

#76 Add performance benchmark for HTTP/JSON to gRPC
  .gitignore
  WORKSPACE
  perf_benchmark/BUILD
  perf_benchmark/README.md
  perf_benchmark/benchmark.proto
  perf_benchmark/benchmark_input_stream.cc
  perf_benchmark/benchmark_input_stream.h
  perf_benchmark/benchmark_input_stream_test.cc
  perf_benchmark/benchmark_input_stream_translator_integration_test.cc
  perf_benchmark/benchmark_main.cc
  perf_benchmark/benchmark_service.textproto
  perf_benchmark/utils.cc
  perf_benchmark/utils.h
  perf_benchmark/utils_test.cc
  repositories.bzl
Labels: lgtm, approved, ok-to-test, size/XXL

#79 Bump rules_fuzzing dependency to version 0.3.2
  WORKSPACE
Labels: lgtm, approved, size/XS

#81 Add benchmarks for variable bindings
  perf_benchmark/BUILD
  perf_benchmark/benchmark.proto
  perf_benchmark/benchmark_input_stream_translator_integration_test.cc
  perf_benchmark/benchmark_main.cc
  perf_benchmark/benchmark_service.textproto
  perf_benchmark/utils.cc
  perf_benchmark/utils.h
Labels: lgtm, approved, size/L

#80 Add performance benchmark for gRPC to JSON transcoding
  perf_benchmark/BUILD
  perf_benchmark/README.md
  perf_benchmark/benchmark_input_stream.cc
  perf_benchmark/benchmark_input_stream.h
  perf_benchmark/benchmark_input_stream_test.cc
  perf_benchmark/benchmark_input_stream_translator_integration_test.cc
  perf_benchmark/benchmark_main.cc
  perf_benchmark/benchmark_service.textproto
  perf_benchmark/utils.cc
  perf_benchmark/utils.h
  perf_benchmark/utils_test.cc
Labels: lgtm, approved, size/XL

#82 Add Bazel rules to package performance benchmark binary into a Docker image
  .bazelrc
  WORKSPACE
  perf_benchmark/BUILD
  repositories.bzl
Labels: size/M, lgtm, approved

#83 Fix benchmark for gRPC streaming message builder logic to use std::stringstream
  perf_benchmark/benchmark_main.cc
Labels: bug, approved, size/S

#84 Add benchmark results to README
  perf_benchmark/README.md
  perf_benchmark/image/array_length.jpg
  perf_benchmark/image/body_length.jpg
  perf_benchmark/image/nested_layers.jpg
  perf_benchmark/image/num_message_segment.jpg
  perf_benchmark/image/num_variable_bindings.jpg
  perf_benchmark/image/value_data_type.png
  perf_benchmark/image/variable_binding_depth.jpg
Labels: lgtm, approved, size/L
