Repository grpc-ecosystem/grpc-httpjson-transcoding, pull requests merged in 2022-08, with the labels that each got.

#72 Update README with prow integration details
  README.md
Labels: lgtm, approved, size/XS

#74 fix the script to format code
  README.md
  script/check-style
  src/include/grpc_transcoding/percent_encoding.h
  src/include/grpc_transcoding/request_weaver.h
  src/include/grpc_transcoding/status_error_listener.h
  src/include/grpc_transcoding/type_helper.h
  src/message_reader.cc
  src/request_stream_translator.cc
  src/request_weaver.cc
  src/type_helper.cc
  test/http_template_fuzz_test.cc
  test/json_request_translator_test.cc
  test/message_reader_fuzz_test.cc
  test/message_reader_test.cc
  test/path_matcher_test.cc
  test/proto_stream_tester.cc
  test/request_weaver_test.cc
  test/response_to_json_translator_test.cc
  test/status_error_listener_test.cc
  test/type_helper_test.cc
Labels: lgtm, approved, size/L

#73 Add newline-delimited JSON response configuration
  README.md
  src/include/grpc_transcoding/response_to_json_translator.h
  src/response_to_json_translator.cc
  test/response_to_json_translator_test.cc
Labels: lgtm, approved, ok-to-test, size/L

#75 Support non uppper case enum values
  src/include/grpc_transcoding/request_message_translator.h
  src/request_message_translator.cc
  test/bookstore.proto
  test/request_message_translator_test.cc
  test/response_to_json_translator_test.cc
  test/testdata/bookstore_service.pb.txt
  test/type_helper_test.cc
Labels: lgtm, approved, size/L
